DROP TABLE IF EXISTS submission;

DROP TABLE IF EXISTS sc;

DROP TABLE IF EXISTS assignment;

DROP TABLE IF EXISTS courses;

DROP TABLE IF EXISTS teacher;

DROP TABLE IF EXISTS student;

DROP TABLE IF EXISTS classes;